version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: [ "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb" ]
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/shell/" ]
      interval: 5s
      timeout: 2s
      retries: 10

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: ap-northeast-1
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DEBUG=0
    volumes:
      - "./.localstack:/var/lib/localstack"
