server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1}
  shutdown: graceful
  forward-headers-strategy: NATIVE
spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
logging:
  level:
    org.springframework: INFO
    org.springframework.security: WARN
    org.springframework.boot.autoconfigure: WARN
    com.github.moriakira.jibundashboard: INFO
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
app:
  security:
    cognito:
      region: ${AWS_REGION:ap-northeast-1}
  dynamodb:
    region: ${AWS_REGION:ap-northeast-1}
    tables:
      users: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-users
      resources-i18n: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-resources-i18n
      settings: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-settings
      salaries: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-salaries
      qualifications: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-qualifications
      salary-ocr-tasks: ${APP_NAME:jibun-dashboard}-${ENV_NAME:local}-salary-ocr-tasks
  s3:
    region: ${AWS_REGION:ap-northeast-1}
    uploads-bucket:
      name: ${UPLOADS_BUCKET_NAME}
      default-expires-in-seconds: ${UPLOADS_BUCKET_DEFAULT_EXPIRES_IN:3600}
  sqs:
    region: ${AWS_REGION:ap-northeast-1}
    salary-ocr-queue:
      url: ${SALARY_OCR_QUEUE_URL:}
