spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
app:
  security:
    local:
      hs256-secret: "piMH6U2uU9_TYC1kx_Mqp4KJDJd0OZK_"
      issuer: "http://localhost/dev-issuer"
      client-id: "jibun-dashboard-local"
  dynamodb:
    endpoint: http://localhost:8000
  s3:
    endpoint: http://localhost:4566
    enable-path-style-access: true
  sqs:
    endpoint: http://localhost:4566
